version: "3"
services:
  discord-chat-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-chat-bot-openai
    restart: unless-stopped
    environment:
      - CHAT_SERVICE=openai
      - DISCORD_BOT_TOKEN=
      - DISCORD_CLIENT_ID=
      - ALLOWED_SERVER_IDS=