version: "3"
services:
  discord-chat-bot:
    build:
      context: docker-compose
      dockerfile: Dockerfile
    container_name: discord-chat-bot-openai
    restart: unless-stopped
    environment:
      - CHAT_SERVICE=openai