version: "3"
services:
  # Comment this out if not using VPN
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    volumes:
      - ./gluetun:/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=Japan
      - FREE_ONLY=true
    restart: unless-stopped

  discord-chat-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-chat-bot
    restart: unless-stopped
    # Comment this out if not using VPN
    network_mode: "service:gluetun"