version: "3"

services:
  discord-chat-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-chat-bot-genai
    restart: unless-stopped
    network_mode: "container:gluetun"
    environment:
      - CHAT_SERVICE=genai
      - DISCORD_BOT_TOKEN=
      - DISCORD_CLIENT_ID=
      - ALLOWED_SERVER_IDS=