SECONDS_DELAY_RECEIVING_MSG = (
    3  # give a delay for the bot to respond, so it can catch multiple messages
)
MAX_THREAD_MESSAGES = 200
ACTIVATE_THREAD_PREFIX = "💬✅"
INACTIVATE_THREAD_PREFIX = "💬❌"
MAX_CHARS_PER_REPLY_MSG = (
    1500  # message has a 2k limit, we just break message into 1.5k
)
EMBED_TITLE_LENGTH = 256
EMBED_DESCRIPTION_LENGTH = 4096
EMBED_FIELD_COUNT = 25
EMBED_FIELD_NAME_LENGTH = 256
EMBED_FIELD_VALUE_LENGTH = 1024
EMBED_FOOTER_LENGTH = 2048
EMBED_AUTHOR_NAME_LENGTH = 256
EMBED_TOTAL_LENGTH = 6000
